DELETE from Products;

INSERT INTO Products VALUES(1,'Aero','Aero Bar',0.75,'/assets/chocolate/bars/aero.jpg',100,'chocolatebar');
INSERT INTO Products VALUES(2,'Aero Mint','Mint Aero Bar',0.75,'/assets/chocolate/bars/aero.jpg',100,'chocolatebar');
INSERT INTO Products VALUES(3,'Bounty','Chocolate bar with choconut filling',0.75,'/assets/chocolate/bars/bounty.jpg',100,'chocolatebar');
INSERT INTO Products VALUES(4,'Crunchie','Chocolate bar with honeycomb filling',0.63,'/assets/chocolate/bars/cadburycrunchie.jpg',1000,'chocolatebar');
INSERT INTO Products VALUES(5,'Cadbury Dairy Bar','Dairy milk chocolate',0.20,'/assets/chocolate/bars/cadburydairybar.jpg',200,'chocolatebar');
INSERT INTO Products VALUES(6,'Cadbury Dairy Caramel','Dairy milk with caramel filling',0.99,'/assets/chocolate/bars/cadburydairycaramel.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(7,'Cadbury Twirl','Chocolate',0.70,'/assets/chocolate/bars/cadburytwirl.jpg',600,'chocolatebar');	  
INSERT INTO Products VALUES(8,'Cadbury Whispa','Whispa',0.60,'/assets/chocolate/bars/cadburywispa.jpg',900,'chocolatebar');
INSERT INTO Products VALUES(9,'Freddo Bars','Chocolate bars',0.20,'/assets/chocolate/bars/freddobars.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(10,'Frys Turkish Delight','Turkish delight covered with milk chocolate',0.99,'/assets/chocolate/bars/frysturkishdelight.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(11,'Galaxy Ripple','Ripple',0.99,'/assets/chocolate/bars/galaxyripple.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(12,'Kinder Bueno','Bueno',0.20,'/assets/chocolate/bars/kinderbueno.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(13,'Kinder Mini Treats','Miini treats',0.20,'/assets/chocolate/bars/kinderminitreats.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(14,'Kitkat','Kitkat',0.20,'/assets/chocolate/bars/kitkat.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(15,'Kitkat Chunky','Kitkat chunky',0.20,'/assets/chocolate/bars/kitkatchunky.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(16,'Lion Bar','Lion Bar',0.20,'/assets/chocolate/bars/lionbar.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(17,'Mars Bars multipack','MarsBars',0.20,'/assets/chocolate/bars/marsmultipack.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(18,'Milky Bar','Milky Bar',0.20,'/assets/chocolate/bars/milkybar.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(19,'Rolos','Rolos',0.20,'/assets/chocolate/bars/rolo.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(20,'Snickers','Snickers',0.20,'/assets/chocolate/bars/snickersmultipack.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(21,'Toffee Crisp','Toffee Crisp',0.20,'/assets/chocolate/bars/toffeecrisp.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(22,'Yorkie','Yorkie',0.20,'/assets/chocolate/bars/yorkie.jpg',400,'chocolatebar');
INSERT INTO Products VALUES(23,'Assorted Chocolate Truffles','Assortment of chocolate truffles',0.75,'/assets/chocolate/boxes/assortedchocolatetruffles.jpg',100,'chocolateboxes');
INSERT INTO Products VALUES(24,'Cadbury Milk Tray','Selection of Cadbury milk chocolate',0.75,'/assets/chocolate/boxes/cadburymilktray.jpg',100,'chocolateboxes');
INSERT INTO Products VALUES(25,'Cadbury Heroes','Mixed box of Cadbury chocolate',0.75,'/assets/chocolate/boxes/cadburyheroes.jpg',100,'chocolateboxes');
INSERT INTO Products VALUES(26,'Cadbury Roses','Selection of Cadbury sweets',0.63,'/assets/chocolate/boxes/cadburyroses.jpg',1000,'chocolateboxes');
INSERT INTO Products VALUES(27,'Cadbury small selection','Small selection of Cadbury chocolate',0.20,'/assets/chocolate/boxes/cadburysmallselection.jpg',200,'chocolateboxes');
INSERT INTO Products VALUES(28,'Celebrations','Selection of chocolate',0.99,'/assets/chocolate/boxes/celebrations.jpg',400,'chocolateboxes');
INSERT INTO Products VALUES(29,'Chocolate Orange','Orange chocolate segments',0.70,'/assets/chocolate/boxes/chocolateorange.jpg',600,'chocolateboxes');
INSERT INTO Products VALUES(30,'Ferrero Rocher','Dark chocolate with chocolate and nut filling',0.60,'/assets/chocolate/boxes/ferrerorocher.jpg',900,'chocolateboxes');
INSERT INTO Products VALUES(31,'Freddo Selection','Selection of Freddo chocolate',0.20,'/assets/chocolate/boxes/freddoselection.jpg',400,'chocolateboxes');
INSERT INTO Products VALUES(32,'Milk Chocolate Truffles','Milk  chocolate truffles',0.99,'/assets/chocolate/boxes/lindtchocolatetruffles.jpg',400,'chocolateboxes');
INSERT INTO Products VALUES(33,'Dark Chocolate Truffles','Dark  chocolate truffles',0.99,'/assets/chocolate/boxes/lindtdarkchocolatetruffles.jpg',400,'chocolateboxes');
INSERT INTO Products VALUES(34,'Quality Street tub','Tub of Quality street chooclates',0.20,'/assets/chocolate/boxes/qualitystreettub.jpg',400,'chocolateboxes');
INSERT INTO Products VALUES(35,'Beechs Mint Chocolate','Mint chocolates',0.75,'/assets/chocolate/mint/beechsmintchocolates.jpeg',100,'mintchocolates');
INSERT INTO Products VALUES(36,'Bendicks Mint Chocolate Collection','Mint chocolates',0.75,'/assets/chocolate/mint/bendicksmintcollection.jpeg',100,'chocolateboxes');
INSERT INTO Products VALUES(37,'Dark Chocolate Mints','Mint chocolates',0.75,'/assets/chocolate/mint/darkmintcrisp.jpeg',100,'chocolateboxes');
INSERT INTO Products VALUES(38,'Kit Kat Duos','Mint chocolates',0.75,'/assets/chocolate/mint/kitkatduos.jpeg',100,'chocolateboxes');
INSERT INTO Products VALUES(39,'Lindt Mint Chocolates','Mint chocolates',0.75,'/assets/chocolate/mint/lindtmintchocolates.jpeg',100,'chocolateboxes');
INSERT INTO Products VALUES(40,'Mint Chocolate Selection','Mint chocolates',0.75,'/assets/chocolate/mint/mintchocolateselection.jpeg',100,'chocolateboxes');
INSERT INTO Products VALUES(41,'Mint Thins','Mint chocolates',0.75,'/assets/chocolate/mint/mintthins.jpeg',100,'chocolateboxes');
INSERT INTO Products VALUES(42,'Thorntons Mint Chocolates','Mint chocolates',0.75,'/assets/chocolate/mint/thorntonsmints.jpeg',100,'chocolateboxes');
INSERT INTO Products VALUES(43,'Whittakers Mint Chocolates','Mint chocolates',0.75,'/assets/chocolate/mint/whittakersmints.jpeg',100,'chocolateboxes');
INSERT INTO Products VALUES(44,'Refresher Bars','Chewy sweet bars with a tangy inside',0.75,'/assets/retrosweets/refresherbars.jpg',100,'retrosweets');
INSERT INTO Products VALUES(45,'Sherbert pips','Shertbert sweets',0.63,'/assets/retrosweets/sherbertpips.jpg',1000,'retrosweets');
INSERT INTO Products VALUES(46,'Love hearts','Love hearts with messages',0.20,'/assets/retrosweets/lovehearts.png',200,'retrosweets');
INSERT INTO Products VALUES(47,'Barley Sugar','Barley sweets',0.99,'/assets/retrosweets/barley-sugar.jpg',400,'retrosweets');
INSERT INTO Products VALUES(48,'Sherbert Fountain','Sherbert with liquorice dipper',0.70,'/assets/retrosweets/sherbertfountain.jpeg',600,'retrosweets');
INSERT INTO Products VALUES(49,'Fizzy rings','Fizzy rings',0.60,'/assets/retrosweets/fizzyrings.jpg',900,'retrosweets');
INSERT INTO Products VALUES(50,'Fizzy cola bottles','Bubble gum',0.20,'/assets/retrosweets/colabottles.jpeg',400,'retrosweets');
INSERT INTO Products VALUES(51,'Foam bananas','Banana flavoured sweets',0.99,'/assets/retrosweets/foambananas.jpg',400,'retrosweets');
INSERT INTO Products VALUES(52,'Blackjacks','Chewy liquorice sweets',0.50,'/assets/retrosweets/blackjacks.jpeg',900,'retrosweets');
INSERT INTO Products VALUES(53,'Blackcurrant jellies','Blackcurrant flavoured jelly sweets',0.20,'/assets/retrosweets/blackcurrantjellies.jpeg',400,'retrosweets');
INSERT INTO Products VALUES(54,'Aniseed Twists','Aniseed flavoured boiled sweets',0.99,'/assets/retrosweets/aniseedtwists.jpeg',400,'retrosweets');
INSERT INTO Products VALUES(55,'Fizzy Cola bottles','Cola bottles',0.60,'/assets/retrosweets/colabottles.jpeg',1000,'retrosweets');
INSERT INTO Products VALUES(56,'Flying saucers','Sherbert in rice-paper',0.20,'/assets/retrosweets/flyingsaucers.jpeg',200,'retrosweets');
INSERT INTO Products VALUES(57,'Gobstoppers','Gobstoppers',0.68,'/assets/retrosweets/gobstoppers.jpg',600,'retrosweets');
INSERT INTO Products VALUES(58,'Fizzy rings','Fizzy rings',0.60,'/assets/retrosweets/fizzyrings.jpg',900,'retrosweets');
INSERT INTO Products VALUES(59,'Candy Apples','Candyyyyyyyyyy',0.99,'/assets/retrosweets/toffee.jpeg',400,'retrosweets');
INSERT INTO Products VALUES(60,'Bubble gum','Bubble gum',0.20,'/assets/retrosweets/gum.jpg',400,'retrosweets');
INSERT INTO Products VALUES(61,'Nerds','Sour sweets in different flavoured',0.99,'/assets/retrosweets/nerds.webp',400,'retrosweets');
INSERT INTO Products VALUES(62,'Double lollies','Fruit flavoured lollipops',0.99,'/assets/lollipops/double-lollies.jpg',400,'lollipops');
INSERT INTO Products VALUES(63,'Drumstick lollipops','Chewy fruit flavoured lollipops',0.99,'/assets/lollipops/drumstick-lolly-sweets.jpg',400,'lollipops');
INSERT INTO Products VALUES(64,'Fruit lollipops','Fruit flavoured lollipops',0.99,'/assets/lollipops/fruity_lollies_loose.jpg',400,'lollipops');
INSERT INTO Products VALUES(65,'Jumbo traffic light lollipops','Three-flavoured lollipops',0.99,'/assets/lollipops/jumbo-traffic-light-lollies.jpg',400,'lollipops');
INSERT INTO Products VALUES(66,'Sherbert Dip-Dabs','Lollipops with sherbert',0.99,'/assets/lollipops/sherbet-dip-dab.jpg',400,'lollipops');
INSERT INTO Products VALUES(67,'Tongue-painter lollipops','Fruit flavoured lollipops',0.99,'/assets/lollipops/tongue_painter_loose.jpg',400,'lollipops');
INSERT INTO Products VALUES(68,'Fruit lollipops','Fruit flavoured lollipops',0.99,'/assets/lollipops/fruity_lollies_loose.jpg',400,'lollipops');
INSERT INTO Products VALUES(69,'Vimto lollipops','Vimto flavoured lollipops',0.99,'/assets/lollipops/vimto-lollies.jpg',400,'lollipops');
INSERT INTO Products VALUES(70,'Acid drops','Sour boiled sweets',0.99,'/assets/boiledsweets/aciddrops.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(71,'Aniseed twists','Aniseed flavoured boiled sweets',0.99,'/assets/boiledsweets/aniseed-twist-sweets.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(72,'Apple and cinnamon sweets','Apple and cinnamon flavoured boiled sweets',0.99,'/assets/boiledsweets/apple-and-cinnamon-sweets.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(73,'Apple and custard sweets','Apple and custard flavoured boiled sweets',0.99,'/assets/boiledsweets/apple-and-custard-sweets.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(74,'Army and navy sweets','Flavoured boiled sweets',0.99,'/assets/boiledsweets/army-and-navy-boiled-sweets.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(75,'Aniseed twists','Aniseed flavoured boiled sweets',0.99,'/assets/boiledsweets/aniseed-twist-sweets.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(76,'Banana and mango sweets','Banana and mango flavoured boiled sweets',0.99,'/assets/boiledsweets/banana-and-mango.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(77,'Aniseed twists','Aniseed flavoured boiled sweets',0.99,'/assets/boiledsweets/aniseed-twist-sweets.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(78,'Barley sugar','Barley sugar boiled sweets',0.99,'/assets/boiledsweets/barley-sugar.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(79,'Blackcurrant and liquorice','Blackcurrant and liquorice flavoured boiled sweets',0.99,'/assets/boiledsweets/blackcurrant-and-liquorice.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(80,'Bullseyes','Bullseye sweets',0.99,'/assets/boiledsweets/bulls-eyes.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(81,'Buttermints','Buttermint sweets',0.99,'/assets/boiledsweets/buttermints.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(82,'ChocFruit boiled sweets','Chocolate and fruit sweets',0.99,'/assets/boiledsweets/ChocFruits.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(83,'Cola cubes','Colate flavoured cubes',0.99,'/assets/boiledsweets/cola-cubes.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(84,'Cough candy twist','Cough candy',0.99,'/assets/boiledsweets/CoughCandyTwist.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(85,'everton-mints','Everton mints',0.99,'/assets/boiledsweets/everton-mints.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(86,'Foxes glacier fruits','Fruit flavoured boiled sweets',0.99,'/assets/boiledsweets/foxs-glacier-fruits-2-bags.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(87,'Foxes glacier mints','Mint flavoured boiled sweets',0.99,'/assets/boiledsweets/foxs-glacier-fruits-2-bags.jpg',400,'boiledsweets');
INSERT INTO Products VALUES(88,'Apple bon bons','Apple flavoured bon-bons',0.99,'/assets/bonbons/applebonbons.jpeg',400,'bonbons');
INSERT INTO Products VALUES(89,'Lemon bon bons','lemon flavoured bon-bons',0.99,'/assets/bonbons/lemonbonbons.jpeg',400,'bonbons');
INSERT INTO Products VALUES(90,'Raspberry bon bons','Raspberry flavoured bon-bons',0.99,'/assets/bonbons/raspberrybonbons.jpeg',400,'bonbons');
INSERT INTO Products VALUES(91,'Strawberry bon bons','Strawberry flavoured bon-bons',0.99,'/assets/bonbons/strawberrybonbons.jpeg',400,'bonbons');
INSERT INTO Products VALUES(92,'Toffee bon bons','Toffee flavoured bon-bons',0.99,'/assets/bonbons/toffeebonbons.jpeg',400,'bonbons');
INSERT INTO Products VALUES(93,'Black Jacks','Liquorice sweets',0.99,'/assets/liquorice/blackjacks.jpg',400,'liquorice');
INSERT INTO Products VALUES(94,'Black Jacks','Liquorice sweets',0.99,'/assets/liquorice/blackjacks.jpg',400,'liquorice');
INSERT INTO Products VALUES(95,'Lion liquorice','Liquorice sweets',0.99,'/assets/liquorice/lion-liquorice.jpg',400,'liquorice');
INSERT INTO Products VALUES(96,'Liquorice Torpedos','Liquorice in a sweet shell',0.99,'/assets/liquorice/liquoricetorpedos.jpg',400,'liquorice');
INSERT INTO Products VALUES(97,'Maynard AllSorts','Liquorice sweets',0.99,'/assets/liquorice/maynard-allsorts.jpg',400,'liquorice');
INSERT INTO Products VALUES(98,'Pontefract','Liquorice sweets',0.99,'/assets/liquorice/pontefract.jpg',400,'liquorice');
INSERT INTO Products VALUES(99,'Candy canes','Mint candy canes',1.30,'/assets/specialoccasions/christmas/candy_canes.webp',400,'christmas');
INSERT INTO Products VALUES(100,'Christmas Dairy Milk selection','Cadbury Dairy Milk selection box',1.30,'/assets/specialoccasions/christmas/christmas_dairy_milk.webp',400,'christmas');
INSERT INTO Products VALUES(101,'Christmas Lollipops','Christmas lollipops',1.20,'/assets/specialoccasions/christmas/christmas_lollipops.webp',400,'christmas');
INSERT INTO Products VALUES(102,'Christmas selection bag','Bags of christmas sweets',1.30,'/assets/specialoccasions/christmas/christmas_selection_bag.webp',400,'christmas');
INSERT INTO Products VALUES(103,'Christmas sweets','Bags of christmas sweets',1.30,'/assets/specialoccasions/christmas/christmas_sweet_bags.webp',400,'christmas');
INSERT INTO Products VALUES(104,'Christmas sweet jar','Jars of christmas sweets',1.30,'/assets/specialoccasions/christmas/christmas_sweet_jar.webp',400,'christmas');
INSERT INTO Products VALUES(105,'Hotel Chocolat Chocolates','Box of Hotel Chocolat Christmas chocolates',1.30,'/assets/specialoccasions/christmas/hotel_chocolat.webp',400,'christmas');
INSERT INTO Products VALUES(106,'Lindor Christmas crackers','Christmas crakcers filled with chocolates',1.30,'/assets/specialoccasions/christmas/lindor_christmas_crackers.webp',400,'christmas');
INSERT INTO Products VALUES(107,'Lindt Festive chocolate selection','Bags of christmas sweets',1.30,'/assets/specialoccasions/christmas/lindt_festive_selection.webp',400,'christmas');
INSERT INTO Products VALUES(108,'Chocolate hearts','Chocolate hearts',1.30,'/assets/specialoccasions/valentines/chocolate_hearts.webp',400,'valentines');
INSERT INTO Products VALUES(109,'Chocolate red roses','Chocolate roses',1.30,'/assets/specialoccasions/valentines/chocolate_red_roses.webp',400,'valentines');
INSERT INTO Products VALUES(110,'Heart lollipops','Heart shaped lollipops',1.30,'/assets/specialoccasions/valentines/heart_lollipops.webp',400,'valentines');
INSERT INTO Products VALUES(111,'Valentine kisses','Red candy lips',1.30,'/assets/specialoccasions/valentines/kisses.webp',400,'valentines');
INSERT INTO Products VALUES(112,'Love hearts Pick-and-Mix box','Love heart candies with other sweets in a pix and mix box',1.30,'/assets/specialoccasions/valentines/love_hearts_pink_and_mix_box.webp',400,'valentines');
INSERT INTO Products VALUES(113,'Love hearts sweets','Love heart candies',1.30,'/assets/specialoccasions/valentines/love_hearts_sweets.webp',400,'valentines');
INSERT INTO Products VALUES(114,'Youre one in a million sweets','Sweets in a custom box',1.30,'/assets/specialoccasions/valentines/one_in_a_million_sweets.webp',400,'valentines');
INSERT INTO Products VALUES(115,'Pink candy hearts','Pink candy hearts covered in sprinkles',1.30,'/assets/specialoccasions/valentines/pink_candy_hearts.webp',400,'valentines');
INSERT INTO Products VALUES(116,'Red candy hearts','Red heart-shaped candies',1.30,'/assets/specialoccasions/valentines/red_chocolate_hearts.webp',400,'valentines');
INSERT INTO Products VALUES(117,'Valentines sweet boxes','Assorted valentines sweets in a gift box',1.30,'/assets/specialoccasions/valentines/sweet_boxes.webp',400,'valentines');
INSERT INTO Products VALUES(118,'Valentines sweet cones','Valentines sweets in a cone',1.30,'/assets/specialoccasions/valentines/sweet_cones.webp',400,'valentines');
INSERT INTO Products VALUES(119,'Valentines sweets','Assorted valentines sweets in a gift box',1.30,'/assets/specialoccasions/valentines/sweet_gift_box.webp',400,'valentines');
INSERT INTO Products VALUES(120,'Valentines sweet hamper','Assorted valentines sweets in a hamper',1.30,'/assets/specialoccasions/valentines/sweet_hamper.webp',400,'valentines');
INSERT INTO Products VALUES(121,'Valentines sweet bags','Bag of valentines sweets',1.30,'/assets/specialoccasions/valentines/valentine_sweet_bags.webp',400,'valentines');
INSERT INTO Products VALUES(122,'Cadbury Oreo egg','Oreo easter egg',1.30,'/assets/specialoccasions/easter/cadbury_oreo_egg.webp',400,'easter');
INSERT INTO Products VALUES(123,'Cadbury Galaxy mini easter eggs','Cadbury Galaxy easter eggs',1.30,'/assets/specialoccasions/easter/cadbury_galaxy_mini_easter_eggs.webp',400,'easter');
INSERT INTO Products VALUES(124,'Cadbury Creme eggs','Chocolate eggs filled with fondant',1.30,'/assets/specialoccasions/easter/cadburys_creme_eggs.webp',400,'easter');
INSERT INTO Products VALUES(125,'Cadburys Frys easter eggs','Cadburys Frys easter eggs',1.30,'/assets/specialoccasions/easter/cadburys_frys_easter_egg.jpg',400,'easter');
INSERT INTO Products VALUES(126,'Cadbury white chocolate bunny','White chocolate bunny',1.30,'/assets/specialoccasions/easter/cadbury_white_chocolate_bunny.jpg',400,'easter');
INSERT INTO Products VALUES(127,'Cadbury fruit and nut easter egg','Cadbury Fruit and Nut easter eggs',1.30,'/assets/specialoccasions/easter/dairy_fruit_and_nut_egg.jpg',400,'easter');
INSERT INTO Products VALUES(128,'Cadbury Dairy milk chocolate bunny','Cadbury Dairy milk bunny',1.30,'/assets/specialoccasions/easter/dairy_milk_bunny.jpg',400,'easter');
INSERT INTO Products VALUES(129,'Easter bunny sweets','Easter bunny sweets',1.30,'/assets/specialoccasions/easter/easter_bunnies.webp',400,'easter');
INSERT INTO Products VALUES(130,'Easter Cone','Cone of easter sweets',1.30,'/assets/specialoccasions/easter/easter_cone.webp',400,'easter');
INSERT INTO Products VALUES(131,'Easter cone','Cone of easter sweets',1.30,'/assets/specialoccasions/easter/easter_cone.webp',400,'easter');
INSERT INTO Products VALUES(132,'Kinder Suprise easter egg','Kinder Suprise easter egg',1.30,'/assets/specialoccasions/easter/kinder_suprise_egg.webp',400,'easter');
INSERT INTO Products VALUES(133,'Turkish Delight easter egg','Turkish Delight easter egg',1.30,'/assets/specialoccasions/easter/turkish_delight_easter_egg.jpg',400,'easter');
INSERT INTO Products VALUES(134,'Wine Gums easter egg','Wine Gums easter egg',1.30,'/assets/specialoccasions/easter/wine_gums_easter_egg.jpg',400,'easter');
INSERT INTO Products VALUES(135,'Bloody skulls','Gummy skulls',1.30,'/assets/specialoccasions/halloween/skulls.webp',400,'halloween');
INSERT INTO Products VALUES(136,'Bloody skulls','Skull candy',1.30,'/assets/specialoccasions/halloween/blood_skulls.webp',400,'halloween');
INSERT INTO Products VALUES(137,'Bloody eyes','Gummy eyes',1.30,'/assets/specialoccasions/halloween/bloody_eyes.webp',400,'halloween');
INSERT INTO Products VALUES(138,'Dead fingers','Green zombie fingers',1.30,'/assets/specialoccasions/halloween/dead_fingers.webp',400,'halloween');
INSERT INTO Products VALUES(139,'Dracula fangs','Candy vampire fangs',1.30,'/assets/specialoccasions/halloween/dracula_fangs.webp',400,'halloween');
INSERT INTO Products VALUES(140,'Glow worms','Candy worms',1.30,'/assets/specialoccasions/halloween/glow_worms.webp',400,'halloween');
INSERT INTO Products VALUES(141,'Hallween cats','Candy halloweeen cats',1.30,'/assets/specialoccasions/halloween/halloween_cats.webp',400,'halloween');
INSERT INTO Products VALUES(142,'Halloween treats selection','Halloween treats selection',1.30,'/assets/specialoccasions/halloween/halloween_treats_selection.webp',400,'halloween');
INSERT INTO Products VALUES(143,'Horror heads','Candy monster heads',1.30,'/assets/specialoccasions/halloween/horror_heads.webp',400,'halloween');
INSERT INTO Products VALUES(144,'Marshmallow pumpkins','Marshmallow pumpkins',1.30,'/assets/specialoccasions/halloween/marshmallow_pumpkins.webp',400,'halloween');
INSERT INTO Products VALUES(145,'Monster treats','Monster-shaped treats',1.30,'/assets/specialoccasions/halloween/monster_treats.webp',400,'halloween');
INSERT INTO Products VALUES(146,'Pumpkin gummies','Pumpkin gummy sweets',1.30,'/assets/specialoccasions/halloween/pumpkin_gummies.webp',400,'halloween');
INSERT INTO Products VALUES(147,'Halloween skulls','Skull-shaped sweets',1.30,'/assets/specialoccasions/halloween/skulls.webp',400,'halloween');
INSERT INTO Products VALUES(148,'Halloween sour spiders','Spider-shaped sour sweets',1.30,'/assets/specialoccasions/halloween/sour_spiders.webp',400,'halloween');
INSERT INTO Products VALUES(149,'Halloween sour sweet jars','Jar of halloween sour sweets',1.30,'/assets/specialoccasions/halloween/sour_times.webp',400,'halloween');
INSERT INTO Products VALUES(150,'Trick or treats','Mixed bag of halloween sweets',1.30,'/assets/specialoccasions/halloween/trick_or_treats.webp',400,'halloween');
INSERT INTO Products VALUES(151,'Trolli halloween sweets','Mixed bag of halloween sweets',1.30,'/assets/specialoccasions/halloween/trolli_halloween_sweets.webp',400,'halloween');
INSERT INTO Products VALUES(152,'Witches heads','Candy witch heads',1.30,'/assets/specialoccasions/halloween/witches_heads.webp',400,'halloween');
INSERT INTO Products VALUES(153,'Clotted cream fudge','Clotted cream fudge',1.30,'/assets/fudge/clotted_cream_fudge.webp',400,'fudge');
INSERT INTO Products VALUES(154,'Fudge selection box','Mixed box of fudge',1.30,'/assets/fudge/fudge_box.webp',400,'fudge');
INSERT INTO Products VALUES(155,'Fudge gift box','Mixed fudge gift box',1.30,'/assets/fudge/fudge_gift_box.webp',400,'fudge');
INSERT INTO Products VALUES(156,'Fudge selection box','Mixed fudge gift box',1.30,'/assets/fudge/fudge_selection_box.webp',400,'fudge');
INSERT INTO Products VALUES(157,'Fudge taster box','Taster box of fudge',1.30,'/assets/fudge/fudge_taster_box.webp',400,'fudge');
INSERT INTO Products VALUES(158,'Funky fudge','Box of funky fudge',1.30,'/assets/fudge/funky_fudge_box.webp',400,'fudge');
INSERT INTO Products VALUES(159,'Gingerbread fudge','Gingerbread flavoured fudge',1.30,'/assets/fudge/gingerbread_fudge.webp',400,'fudge');
INSERT INTO Products VALUES(160,'Ginger fudge','Ginger flavoured fudge',1.30,'/assets/fudge/ginger_fudge.webp',400,'fudge');
INSERT INTO Products VALUES(161,'Salted caramel','Salted fudge',1.30,'/assets/fudge/salted_caramel_fudge.webp',400,'fudge');
INSERT INTO Products VALUES(162,'Strawberry cheesecake fudge','Fudge with strawberry cheesecake topping',1.30,'/assets/fudge/strawberry_cheesecake_fudge.webp',400,'fudge');
INSERT INTO Products VALUES(163,'Vanilla fudge','Vanilla flavoured fudge',1.30,'/assets/fudge/vanilla_fudge.webp',400,'fudge');
INSERT INTO Products VALUES(164,'Walnut fudge','Fudge with walnuts',1.30,'/assets/fudge/walnut_fudge.webp',400,'fudge');

